services:
  app:
    build:
      context: ./app
      target: base
    command: python manage.py runserver 0.0.0.0:${PORT:-1999}
    volumes:
      - ./app:/app
    ports:
      - ${PORT:-1999}:${PORT:-1999}
    environment:
      DB_NAME: dbname
      DB_USER: dbuser
      DB_PASS: dbpass

  db:
    volumes:
      - ./docker/db-dev:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: dbuser
      PMA_PASSWORD: dbpass
