services:
  app:
    env_file: .env
    depends_on:
      - db

  scraper:
    build: ./scraper
    user: node
    init: true
    mem_limit: 300M
    memswap_limit: 1G
    restart: on-failure:3
    environment:
      - NODE_ENV=production

  db:
    image: mariadb:11.2
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure:3

volumes:
  db_data:
