services:
  app:
    # TODO: command
    volumes:
      - static:/app/static_root
      - ./app/assets:/app/assets

  nginx:
    image: nginx:alpine
    ports:
      - ${PORT:-1999}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/public:ro
      - ./assets:/assets:ro
    depends_on:
      - app
    restart: on-failure:3

  db:
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

volumes:
  static:
